package kma.online_exam.models;
// Generated Oct 9, 2020 11:19:13 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DethiCauhoi generated by hbm2java
 */
@Entity
@Table(name="dethicauhoi"
    ,catalog="onlineexam"
)
public class DethiCauhoi  implements java.io.Serializable {


     private int id;
     private Cauhoi cauhoi;
     private Dethi dethi;

    public DethiCauhoi() {
    }

    public DethiCauhoi(Cauhoi cauhoi, Dethi dethi) {
       this.cauhoi = cauhoi;
       this.dethi = dethi;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="questionid")
    public Cauhoi getCauhoi() {
        return this.cauhoi;
    }
    
    public void setCauhoi(Cauhoi cauhoi) {
        this.cauhoi = cauhoi;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="examid")
    public Dethi getDethi() {
        return this.dethi;
    }
    
    public void setDethi(Dethi dethi) {
        this.dethi = dethi;
    }




}


