package kma.online_exam.models;
// Generated Oct 9, 2020 11:19:13 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Lichsuthi generated by hbm2java
 */
@Entity
@Table(name="lichsuthi"
    ,catalog="onlineexam"
)
public class Lichsuthi  implements java.io.Serializable {


     private int id;
     private Sinhvien sinhvien;
     private String examname;
     private Date ngaythi;
     private Integer tglambai;
     private Double diem;
     private String mon;

    public Lichsuthi() {
    }

	
    public Lichsuthi(int id) {
        this.id = id;
    }
    public Lichsuthi(int id, Sinhvien sinhvien, String examname, Date ngaythi, Integer tglambai, Double diem, String mon) {
       this.id = id;
       this.sinhvien = sinhvien;
       this.examname = examname;
       this.ngaythi = ngaythi;
       this.tglambai = tglambai;
       this.diem = diem;
       this.mon = mon;
    }
   
     @Id 
     @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="masv")
    public Sinhvien getSinhvien() {
        return this.sinhvien;
    }
    
    public void setSinhvien(Sinhvien sinhvien) {
        this.sinhvien = sinhvien;
    }

    
    @Column(name="examname")
    public String getExamname() {
        return this.examname;
    }
    
    public void setExamname(String examname) {
        this.examname = examname;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ngaythi", length=16)
    public Date getNgaythi() {
        return this.ngaythi;
    }
    
    public void setNgaythi(Date ngaythi) {
        this.ngaythi = ngaythi;
    }

    
    @Column(name="tglambai")
    public Integer getTglambai() {
        return this.tglambai;
    }
    
    public void setTglambai(Integer tglambai) {
        this.tglambai = tglambai;
    }

    
    @Column(name="diem", precision=53, scale=0)
    public Double getDiem() {
        return this.diem;
    }
    
    public void setDiem(Double diem) {
        this.diem = diem;
    }

    
    @Column(name="mon")
    public String getMon() {
        return this.mon;
    }
    
    public void setMon(String mon) {
        this.mon = mon;
    }




}


