package kma.online_exam.models;
// Generated Oct 9, 2020 11:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Lophoc generated by hbm2java
 */
@Entity
@Table(name="lophoc"
    ,catalog="onlineexam"
)
public class Lophoc  implements java.io.Serializable {


     private int classid;
     private String classname;
     private String matkhau;
     private Monhoc monhoc;
     private Nhanvien nhanvien;
     private int siso;
     private Set<Ketqua> ketquas = new HashSet<Ketqua>(0);

    public Lophoc() {
    }

	
    public Lophoc(String classname, String matkhau, Monhoc monhoc, int siso) {
        this.classname = classname;
        this.matkhau = matkhau;
        this.monhoc = monhoc;
        this.siso = siso;
    }
    public Lophoc(String classname, String matkhau, Monhoc monhoc, Nhanvien nhanvien, int siso) {
       this.classname = classname;
       this.matkhau = matkhau;
       this.monhoc = monhoc;
       this.nhanvien = nhanvien;
       this.siso = siso;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="classid", unique=true, nullable=false)
    public int getClassid() {
        return this.classid;
    }
    
    public void setClassid(int classid) {
        this.classid = classid;
    }

    
    @Column(name="classname", nullable=false)
    public String getClassname() {
        return this.classname;
    }
    
    public void setClassname(String classname) {
        this.classname = classname;
    }

    
    @Column(name="matkhau", nullable=false)
    public String getMatkhau() {
        return this.matkhau;
    }
    
    public void setMatkhau(String matkhau) {
        this.matkhau = matkhau;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmonhoc", nullable=false)
    public Monhoc getMonhoc() {
        return this.monhoc;
    }
    
    public void setMonhoc(Monhoc monhoc) {
        this.monhoc = monhoc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usernameGV")
    public Nhanvien getNhanvien() {
        return this.nhanvien;
    }
    
    public void setNhanvien(Nhanvien nhanvien) {
        this.nhanvien = nhanvien;
    }

    
    @Column(name="siso", nullable=false, columnDefinition="int default 0")
    public int getSiso() {
        return this.siso;
    }
    
    public void setSiso(int siso) {
        this.siso = siso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="lophoc")
    public Set<Ketqua> getKetquas() {
        return this.ketquas;
    }
    
    public void setKetquas(Set<Ketqua> ketquas) {
        this.ketquas = ketquas;
    }



}


