package kma.online_exam.models;
// Generated Oct 9, 2020 11:19:13 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name="nhanvien"
    ,catalog="onlineexam"
)
public class Nhanvien  implements java.io.Serializable {


     private String username;
     private Set<Cauhoi> cauhois = new HashSet<Cauhoi>(0);
     private String chucvu;
     private String email;
     private String gioithieu;
     private String hoten;
     private String image;
     private String loaitk;
     private Set<Lophoc> lophocs = new HashSet<Lophoc>(0);
     private String phone;
     private String phongKhoa;
     private Integer userid;

    public Nhanvien() {
    }

	
    public Nhanvien(String username, String email, String hoten, String loaitk, String phongKhoa, Integer userid) {
        this.username = username;
        this.email = email;
        this.hoten = hoten;
        this.loaitk = loaitk;
        this.phongKhoa = phongKhoa;
        this.userid = userid;
    }
    public Nhanvien(String username, Set<Cauhoi> cauhois, String chucvu, String email, String gioithieu, String hoten, String image, String loaitk, Set<Lophoc> lophocs, String phone, String phongKhoa, Integer userid) {
       this.username = username;
       this.cauhois = cauhois;
       this.chucvu = chucvu;
       this.email = email;
       this.gioithieu = gioithieu;
       this.hoten = hoten;
       this.image = image;
       this.loaitk = loaitk;
       this.lophocs = lophocs;
       this.phone = phone;
       this.phongKhoa = phongKhoa;
       this.userid = userid;
    }
   
     @Id 

    
    @Column(name="username", unique=true, nullable=false)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanvien")
    public Set<Cauhoi> getCauhois() {
        return this.cauhois;
    }
    
    public void setCauhois(Set<Cauhoi> cauhois) {
        this.cauhois = cauhois;
    }

    
    @Column(name="chucvu")
    public String getChucvu() {
        return this.chucvu;
    }
    
    public void setChucvu(String chucvu) {
        this.chucvu = chucvu;
    }

    
    @Column(name="email", nullable=false)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="gioithieu")
    public String getGioithieu() {
        return this.gioithieu;
    }
    
    public void setGioithieu(String gioithieu) {
        this.gioithieu = gioithieu;
    }

    
    @Column(name="hoten", nullable=false)
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    
    @Column(name="image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="loaitk", nullable=false)
    public String getLoaitk() {
        return this.loaitk;
    }
    
    public void setLoaitk(String loaitk) {
        this.loaitk = loaitk;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="nhanvien")
    public Set<Lophoc> getLophocs() {
        return this.lophocs;
    }
    
    public void setLophocs(Set<Lophoc> lophocs) {
        this.lophocs = lophocs;
    }

    
    @Column(name="phone")
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="phong_khoa", nullable=false)
    public String getPhongKhoa() {
        return this.phongKhoa;
    }
    
    public void setPhongKhoa(String phongKhoa) {
        this.phongKhoa = phongKhoa;
    }

    
    @Column(name="userid", nullable=false)
    public Integer getUserid() {
        return this.userid;
    }
    
    public void setUserid(Integer userid) {
        this.userid = userid;
    }




}


