package kma.online_exam.models;
// Generated Oct 9, 2020 11:19:13 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Sinhvien generated by hbm2java
 */
@Entity
@Table(name="sinhvien"
    ,catalog="onlineexam"
)
public class Sinhvien  implements java.io.Serializable {


     private String masv;
     private String hoten;
     private String image;
     private Date ngaysinh;
     private boolean gioitinh;
     private String email;
     private String phone;
     private String quequan;
     private int cmnd;
     private int userid;
     private Set<Ketqua> ketquas = new HashSet<Ketqua>(0);
     private Set<SinhvienLop> sinhvienLops = new HashSet<SinhvienLop>(0);
     private Set<Lichsuthi> lichsuthis = new HashSet<Lichsuthi>(0);

    public Sinhvien() {
    }

	
    public Sinhvien(String masv, String hoten, Date ngaysinh, boolean gioitinh, String email, int cmnd) {
        this.masv = masv;
        this.hoten = hoten;
        this.ngaysinh = ngaysinh;
        this.gioitinh = gioitinh;
        this.email = email;
        this.cmnd = cmnd;
    }
    public Sinhvien(String masv, String hoten, String image, Date ngaysinh, boolean gioitinh, String email, String phone, String quequan, int cmnd, int userid, Set<Ketqua> ketquas, Set<SinhvienLop> sinhvienLops, Set<Lichsuthi> lichsuthis) {
       this.masv = masv;
       this.hoten = hoten;
       this.image = image;
       this.ngaysinh = ngaysinh;
       this.gioitinh = gioitinh;
       this.email = email;
       this.phone = phone;
       this.quequan = quequan;
       this.cmnd = cmnd;
       this.userid = userid;
       this.ketquas = ketquas;
       this.sinhvienLops = sinhvienLops;
       this.lichsuthis = lichsuthis;
    }
   
     @Id 

    
    @Column(name="masv", unique=true, nullable=false, length=20)
    public String getMasv() {
        return this.masv;
    }
    
    public void setMasv(String masv) {
        this.masv = masv;
    }

    
    @Column(name="hoten", nullable=false)
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }

    
    @Column(name="image")
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ngaysinh", nullable=false, length=10)
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }

    
    @Column(name="gioitinh", nullable=false)
    public boolean isGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(boolean gioitinh) {
        this.gioitinh = gioitinh;
    }

    
    @Column(name="email", nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="phone", length=12)
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="quequan")
    public String getQuequan() {
        return this.quequan;
    }
    
    public void setQuequan(String quequan) {
        this.quequan = quequan;
    }

    
    @Column(name="cmnd", nullable=false)
    public int getCmnd() {
        return this.cmnd;
    }
    
    public void setCmnd(int cmnd) {
        this.cmnd = cmnd;
    }

    
    @Column(name="userid", nullable=false)
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sinhvien")
    public Set<Ketqua> getKetquas() {
        return this.ketquas;
    }
    
    public void setKetquas(Set<Ketqua> ketquas) {
        this.ketquas = ketquas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sinhvien")
    public Set<SinhvienLop> getSinhvienLops() {
        return this.sinhvienLops;
    }
    
    public void setSinhvienLops(Set<SinhvienLop> sinhvienLops) {
        this.sinhvienLops = sinhvienLops;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="sinhvien")
    public Set<Lichsuthi> getLichsuthis() {
        return this.lichsuthis;
    }
    
    public void setLichsuthis(Set<Lichsuthi> lichsuthis) {
        this.lichsuthis = lichsuthis;
    }




}


