package kma.online_exam.models;
// Generated Oct 9, 2020 11:19:13 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserAccount generated by hbm2java
 */
@Entity
@Table(name="useraccount"
    ,catalog="onlineexam"
)
public class UserAccount  implements java.io.Serializable {


     private int userid;
     private String password;
     private String role;
     private String username;

    public UserAccount() {
    }

    public UserAccount(String password, String role, String username) {
       this.password = password;
       this.role = role;
       this.username = username;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="userid", unique=true, nullable=false)
    public int getUserid() {
        return this.userid;
    }
    
    public void setUserid(int userid) {
        this.userid = userid;
    }

    
    @Column(name="password", nullable=false, length=32)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="role", nullable=false, length=2)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="username", nullable=false, length=20)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }




}


